**Install Tools**

In [1]:
%%bash
apt-get update -qq
apt-get install -y -qq fastqc samtools unzip wget default-jre
pip install -q multiqc ffq

Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 122354 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package openjdk-11-jre-headless:amd64.
Preparing to unpack .../05-openjdk-11-jre-headless_11.0.30+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jre-headless:amd64 (11.0.30+7-1ubuntu1~22.04) ...
Selecting previously unselected package default-jre-headless.
Preparing to unpack .../06-default-jre-headless_2%3a1.11-72build2_amd64.deb ...
Unpacking default-jre-headless (2:1.11-72build2) ...
Selecting previously unselected package openjdk-11-jre:amd64.
Preparing to unpack .../07-openjdk-11-jre_11.0.30+7-1ubuntu1~22.04_amd64.deb ...
Unpacking openjdk-11-jre:amd64 (11.0.30+7-1ubuntu1~22.04) ...
Selecting previously unselected package default-jre.
Preparing to unpack .../08-default-jre_2%3a1.11-72build2_amd64.deb ...
Unpacking default-jre (2:1.11-72build2) ...
Selecting previously unselected package libcommons-math3-java.
Preparing to unpack .../09-libcommons-math3-java_3.6.1-3_all.deb ...
Unpacking libcommons-math3-java (3.6.1-3) ...
Selecting previously unselected package libjbzip2-java.
Preparing to unpack .../10-libjbzip2-java_0.9.1-7_all.deb ...
Unpacking libjbzip2-java (0.9.1-7) ...
Selecting previously unselected package libapache-pom-java.
Preparing to unpack .../11-libapache-pom-java_18-1_all.deb ...
Unpacking libapache-pom-java (18-1) ...
Selecting previously unselected package libcommons-parent-java.
Preparing to unpack .../12-libcommons-parent-java_43-1_all.deb ...
Unpacking libcommons-parent-java (43-1) ...
Selecting previously unselected package libcommons-compress-java.
Preparing to unpack .../13-libcommons-compress-java_1.21-1_all.deb ...
Unpacking libcommons-compress-java (1.21-1) ...
Selecting previously unselected package libcommons-logging-java.
Preparing to unpack .../14-libcommons-logging-java_1.2-2_all.deb ...
Unpacking libcommons-logging-java (1.2-2) ...
Selecting previously unselected package libcommons-jexl2-java.
Preparing to unpack .../15-libcommons-jexl2-java_2.1.1-5_all.deb ...
Unpacking libcommons-jexl2-java (2.1.1-5) ...
Selecting previously unselected package libjson-simple-java.
Preparing to unpack .../16-libjson-simple-java_2.3.0-1_all.deb ...
Unpacking libjson-simple-java (2.3.0-1) ...
Selecting previously unselected package libngs-sdk2:amd64.
Preparing to unpack .../17-libngs-sdk2_2.11.2-3_amd64.deb ...
Unpacking libngs-sdk2:amd64 (2.11.2-3) ...
Selecting previously unselected package libngs-sdk-dev:amd64.
Preparing to unpack .../18-libngs-sdk-dev_2.11.2-3_amd64.deb ...
Unpacking libngs-sdk-dev:amd64 (2.11.2-3) ...
Selecting previously unselected package libngs-java:amd64.
Preparing to unpack .../19-libngs-java_2.11.2-3_amd64.deb ...
Unpacking libngs-java:amd64 (2.11.2-3) ...
Selecting previously unselected package libsnappy-jni.
Preparing to unpack .../20-libsnappy-jni_1.1.8.3-1_amd64.deb ...
Unpacking libsnappy-jni (1.1.8.3-1) ...
Selecting previously unselected package libsnappy-java.
Preparing to unpack .../21-libsnappy-java_1.1.8.3-1_all.deb ...
Unpacking libsnappy-java (1.1.8.3-1) ...
Selecting previously unselected package libhtsjdk-java.
Preparing to unpack .../22-libhtsjdk-java_2.24.1+dfsg-1_all.deb ...
Unpacking libhtsjdk-java (2.24.1+dfsg-1) ...
Selecting previously unselected package libfindbin-libs-perl.
Preparing to unpack .../23-libfindbin-libs-perl_2.190.02-1_all.deb ...
Unpacking libfindbin-libs-perl (2.190.02-1) ...
Selecting previously unselected package libargs4j-java.
Preparing to unpack .../24-libargs4j-java_2.33-1.1_all.deb ...
Unpacking libargs4j-java (2.33-1.1) ...
Selecting previously unselected package libcommons-io-java.
Preparing to unpack .../25-libcommons-io-java_2.11.0-2_all.deb ...
Unpacking libcommons-io-java (2.11.0-2) ...
Selecting previously unselected package libcommons-lang3-java.
Preparing to unpack .../26-libcommons-lang3-java_3.11-1_all.deb ...
Unpacking libcommons-lang3-java (3.11-1) ...
Selecting previously unselected package libsis-base-jni.
Preparing to unpack .../27-libsis-base-jni_18.09~pre1+git20180928.45fbd31+dfsg-3_amd64.deb ...
Unpacking libsis-base-jni (18.09~pre1+git20180928.45fbd31+dfsg-3) ...
Selecting previously unselected package libsis-base-java.
Preparing to unpack .../28-libsis-base-java_18.09~pre1+git20180928.45fbd31+dfsg-3_all.deb ...
Unpacking libsis-base-java (18.09~pre1+git20180928.45fbd31+dfsg-3) ...
Selecting previously unselected package libsis-jhdf5-jni.
Preparing to unpack .../29-libsis-jhdf5-jni_19.04.0+dfsg-4_amd64.deb ...
Unpacking libsis-jhdf5-jni (19.04.0+dfsg-4) ...
Selecting previously unselected package libsis-jhdf5-java.
Preparing to unpack .../30-libsis-jhdf5-java_19.04.0+dfsg-4_all.deb ...
Unpacking libsis-jhdf5-java (19.04.0+dfsg-4) ...
Selecting previously unselected package fastqc.
Preparing to unpack .../31-fastqc_0.11.9+dfsg-5_all.deb ...
Unpacking fastqc (0.11.9+dfsg-5) ...
Selecting previously unselected package fonts-dejavu-core.
Preparing to unpack .../32-fonts-dejavu-core_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-core (2.37-2build1) ...
Selecting previously unselected package fonts-dejavu-extra.
Preparing to unpack .../33-fonts-dejavu-extra_2.37-2build1_all.deb ...
Unpacking fonts-dejavu-extra (2.37-2build1) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../34-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../35-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../36-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../37-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libxxf86dga1:amd64.
Preparing to unpack .../38-libxxf86dga1_2%3a1.1.5-0ubuntu3_amd64.deb ...
Unpacking libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Selecting previously unselected package x11-utils.
Preparing to unpack .../39-x11-utils_7.7+5build2_amd64.deb ...
Unpacking x11-utils (7.7+5build2) ...
Selecting previously unselected package libatk-wrapper-java.
Preparing to unpack .../40-libatk-wrapper-java_0.38.0-5build1_all.deb ...
Unpacking libatk-wrapper-java (0.38.0-5build1) ...
Selecting previously unselected package libatk-wrapper-java-jni:amd64.
Preparing to unpack .../41-libatk-wrapper-java-jni_0.38.0-5build1_amd64.deb ...
Unpacking libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Selecting previously unselected package libhtscodecs2:amd64.
Preparing to unpack .../42-libhtscodecs2_1.1.1-3_amd64.deb ...
Unpacking libhtscodecs2:amd64 (1.1.1-3) ...
Selecting previously unselected package libhts3:amd64.
Preparing to unpack .../43-libhts3_1.13+ds-2build1_amd64.deb ...
Unpacking libhts3:amd64 (1.13+ds-2build1) ...
Selecting previously unselected package samtools.
Preparing to unpack .../44-samtools_1.13-4_amd64.deb ...
Unpacking samtools (1.13-4) ...
Setting up libhtscodecs2:amd64 (1.1.1-3) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libhts3:amd64 (1.13+ds-2build1) ...
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up openjdk-11-jre-headless:amd64 (11.0.30+7-1ubuntu1~22.04) ...
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/jjs to provide /usr/bin/jjs (jjs) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/rmid to provide /usr/bin/rmid (rmid) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/pack200 to provide /usr/bin/pack200 (pack200) in auto mode
update-alternatives: using /usr/lib/jvm/java-11-openjdk-amd64/bin/unpack200 to provide /usr/bin/unpack200 (unpack200) in auto mode
Setting up libngs-sdk2:amd64 (2.11.2-3) ...
Setting up libxxf86dga1:amd64 (2:1.1.5-0ubuntu3) ...
Setting up openjdk-11-jre:amd64 (11.0.30+7-1ubuntu1~22.04) ...
Setting up libfindbin-libs-perl (2.190.02-1) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up libjson-simple-java (2.3.0-1) ...
Setting up samtools (1.13-4) ...
Setting up libsis-base-jni (18.09~pre1+git20180928.45fbd31+dfsg-3) ...
Setting up libapache-pom-java (18-1) ...
Setting up fonts-dejavu-core (2.37-2build1) ...
Setting up libjbzip2-java (0.9.1-7) ...
Setting up libngs-sdk-dev:amd64 (2.11.2-3) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up fonts-dejavu-extra (2.37-2build1) ...
Setting up libcommons-math3-java (3.6.1-3) ...
Setting up libsis-jhdf5-jni (19.04.0+dfsg-4) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libngs-java:amd64 (2.11.2-3) ...
Setting up libsnappy-jni (1.1.8.3-1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libargs4j-java (2.33-1.1) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up default-jre-headless (2:1.11-72build2) ...
Setting up libcommons-parent-java (43-1) ...
Setting up libcommons-logging-java (1.2-2) ...
Setting up default-jre (2:1.11-72build2) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Setting up libcommons-jexl2-java (2.1.1-5) ...
Setting up libcommons-lang3-java (3.11-1) ...
Setting up x11-utils (7.7+5build2) ...
Setting up libsnappy-java (1.1.8.3-1) ...
Setting up libatk-wrapper-java (0.38.0-5build1) ...
Setting up libcommons-compress-java (1.21-1) ...
Setting up libcommons-io-java (2.11.0-2) ...
Setting up libatk-wrapper-java-jni:amd64 (0.38.0-5build1) ...
Setting up libsis-base-java (18.09~pre1+git20180928.45fbd31+dfsg-3) ...
Setting up libhtsjdk-java (2.24.1+dfsg-1) ...
Setting up libsis-jhdf5-java (19.04.0+dfsg-4) ...
Setting up fastqc (0.11.9+dfsg-5) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...
Setting up at-spi2-core (2.44.0-3) ...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 76.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.6/39.6 MB 29.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 8.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 116.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.7/40.7 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 10.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 11.4 MB/s eta 0:00:00

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)

**Download Tools (HISAT2 + Subread)**

In [2]:
%%bash
# HISAT2 (FIXED)
wget -q https://cloud.biohpc.swmed.edu/index.php/s/oTtGWbWjaxsQ2Ho/download -O hisat2.zip
unzip -o -q hisat2.zip   # ← IMPORTANT: -o avoids prompt

# Create symlink safely
HISAT2_PATH=$(find /content -name hisat2 | head -n 1)
ln -sf $HISAT2_PATH /usr/local/bin/hisat2

# Subread (FIXED)
wget -q https://sourceforge.net/projects/subread/files/subread-2.0.6/subread-2.0.6-Linux-x86_64.tar.gz/download -O subread.tar.gz
tar -xzf subread.tar.gz

# Create symlink safely
FEATURE_PATH=$(find /content -name featureCounts | head -n 1)
ln -sf $FEATURE_PATH /usr/local/bin/featureCounts

**Download FASTQ from SRA**

In [3]:
import subprocess, json, urllib.request, os

SRR = "SRR1039508"  # change if needed
os.makedirs("fastq", exist_ok=True)

# Get FASTQ links
result = subprocess.run(["ffq", "--ftp", SRR], capture_output=True, text=True)
links = json.loads(result.stdout)

# Download files
for entry in links:
    url = entry["url"]
    fname = url.split("/")[-1]
    print(f"Downloading {fname}...")
    urllib.request.urlretrieve(url, f"fastq/{fname}")
    print(f"Done: {fname}")

Downloading SRR1039508_1.fastq.gz...
Done: SRR1039508_1.fastq.gz
Downloading SRR1039508_2.fastq.gz...
Done: SRR1039508_2.fastq.gz

**Quality Control (Raw Reads)**

In [4]:
%%bash
mkdir -p qc_raw
fastqc fastq/*.fastq* -o qc_raw -t 2
multiqc qc_raw -o qc_raw

Analysis complete for SRR1039508_2.fastq.gz
Analysis complete for SRR1039508_1.fastq.gz

Started analysis of SRR1039508_1.fastq.gz
Started analysis of SRR1039508_2.fastq.gz
Approx 5% complete for SRR1039508_1.fastq.gz
Approx 5% complete for SRR1039508_2.fastq.gz
Approx 10% complete for SRR1039508_1.fastq.gz
Approx 10% complete for SRR1039508_2.fastq.gz
Approx 15% complete for SRR1039508_1.fastq.gz
Approx 15% complete for SRR1039508_2.fastq.gz
Approx 20% complete for SRR1039508_1.fastq.gz
Approx 20% complete for SRR1039508_2.fastq.gz
Approx 25% complete for SRR1039508_1.fastq.gz
Approx 25% complete for SRR1039508_2.fastq.gz
Approx 30% complete for SRR1039508_1.fastq.gz
Approx 30% complete for SRR1039508_2.fastq.gz
Approx 35% complete for SRR1039508_1.fastq.gz
Approx 35% complete for SRR1039508_2.fastq.gz
Approx 40% complete for SRR1039508_1.fastq.gz
Approx 40% complete for SRR1039508_2.fastq.gz
Approx 45% complete for SRR1039508_1.fastq.gz
Approx 45% complete for SRR1039508_2.fastq.gz
Approx 50% complete for SRR1039508_1.fastq.gz
Approx 50% complete for SRR1039508_2.fastq.gz
Approx 55% complete for SRR1039508_1.fastq.gz
Approx 55% complete for SRR1039508_2.fastq.gz
Approx 60% complete for SRR1039508_1.fastq.gz
Approx 60% complete for SRR1039508_2.fastq.gz
Approx 65% complete for SRR1039508_1.fastq.gz
Approx 65% complete for SRR1039508_2.fastq.gz
Approx 70% complete for SRR1039508_1.fastq.gz
Approx 70% complete for SRR1039508_2.fastq.gz
Approx 75% complete for SRR1039508_1.fastq.gz
Approx 75% complete for SRR1039508_2.fastq.gz
Approx 80% complete for SRR1039508_2.fastq.gz
Approx 80% complete for SRR1039508_1.fastq.gz
Approx 85% complete for SRR1039508_2.fastq.gz
Approx 85% complete for SRR1039508_1.fastq.gz
Approx 90% complete for SRR1039508_2.fastq.gz
Approx 90% complete for SRR1039508_1.fastq.gz
Approx 95% complete for SRR1039508_2.fastq.gz
Approx 95% complete for SRR1039508_1.fastq.gz

/// MultiQC 🔍 v1.33

       file_search | Search path: /content/qc_raw

            fastqc | Found 2 reports

     write_results | Data        : qc_raw/multiqc_data
     write_results | Report      : qc_raw/multiqc_report.html
           multiqc | MultiQC complete

**Download Adapter File**

In [5]:
%%bash
wget -q https://raw.githubusercontent.com/usadellab/Trimmomatic/main/adapters/TruSeq3-PE.fa

**Trimming Reads**

In [6]:
!ls -R | grep -i trimmomatic

In [7]:
%%bash
# Clean old install (important in Colab)
rm -rf trimmomatic-0.39*

# Download again
wget -q https://github.com/usadellab/Trimmomatic/releases/download/v0.39/trimmomatic-0.39.zip
unzip -o -q trimmomatic-0.39.zip

# Download adapters
wget -q https://raw.githubusercontent.com/usadellab/Trimmomatic/main/adapters/TruSeq3-PE.fa

In [8]:
%%bash
mkdir -p trimmed

# Find Trimmomatic jar automatically
TRIM_JAR=$(find /content -name "*trimmomatic*.jar" | head -n 1)

echo "Using:" $TRIM_JAR

R1=$(ls fastq/*_1.fastq* | head -n 1)
R2=$(ls fastq/*_2.fastq* | head -n 1)

java -jar $TRIM_JAR PE \
  $R1 $R2 \
  trimmed/R1_paired.fastq trimmed/R1_unpaired.fastq \
  trimmed/R2_paired.fastq trimmed/R2_unpaired.fastq \
  ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 \
  LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

Using: /content/Trimmomatic-0.39/trimmomatic-0.39.jar

TrimmomaticPE: Started with arguments:
 fastq/SRR1039508_1.fastq.gz fastq/SRR1039508_2.fastq.gz trimmed/R1_paired.fastq trimmed/R1_unpaired.fastq trimmed/R2_paired.fastq trimmed/R2_unpaired.fastq ILLUMINACLIP:TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
Multiple cores found: Using 2 threads
Using PrefixPair: 'TACACTCTTTCCCTACACGACGCTCTTCCGATCT' and 'GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT'
ILLUMINACLIP: Using 1 prefix pairs, 0 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Quality encoding detected as phred33
Input Read Pairs: 22935521 Both Surviving: 22141244 (96.54%) Forward Only Surviving: 351667 (1.53%) Reverse Only Surviving: 340132 (1.48%) Dropped: 102478 (0.45%)
TrimmomaticPE: Completed successfully

**Download HISAT2 Genome Index**

In [9]:
%%bash
wget -q https://genome-idx.s3.amazonaws.com/hisat/grch38_genome.tar.gz
tar -xzf grch38_genome.tar.gz

**Alignment (HISAT2)**

In [10]:
%%bash
hisat2 -x grch38/genome \
  -1 trimmed/R1_paired.fastq \
  -2 trimmed/R2_paired.fastq \
  -S aligned.sam \
  --summary-file alignment_summary.txt

22141244 reads; of these:
  22141244 (100.00%) were paired; of these:
    750201 (3.39%) aligned concordantly 0 times
    20558383 (92.85%) aligned concordantly exactly 1 time
    832660 (3.76%) aligned concordantly >1 times
    ----
    750201 pairs aligned concordantly 0 times; of these:
      118038 (15.73%) aligned discordantly 1 time
    ----
    632163 pairs aligned 0 times concordantly or discordantly; of these:
      1264326 mates make up the pairs; of these:
        749138 (59.25%) aligned 0 times
        454406 (35.94%) aligned exactly 1 time
        60782 (4.81%) aligned >1 times
98.31% overall alignment rate

**Convert + Sort + Index BAM**

In [11]:
%%bash
samtools view -@ 2 -bS aligned.sam > aligned.bam
samtools sort -@ 2 aligned.bam -o aligned_sorted.bam
samtools index aligned_sorted.bam

[bam_sort_core] merging from 14 files and 2 in-memory blocks...

**Download Annotation (GTF)**

In [12]:
%%bash
wget -q ftp://ftp.ensembl.org/pub/release-110/gtf/homo_sapiens/Homo_sapiens.GRCh38.110.gtf.gz
gunzip Homo_sapiens.GRCh38.110.gtf.gz

**Gene Counting (featureCounts)**

In [13]:
%%bash
featureCounts -T 2 -p -B -C \
  -s 0 \
  -a Homo_sapiens.GRCh38.110.gtf \
  -o counts.txt aligned_sorted.bam

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
	  v2.0.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                                                                            ||
||                           aligned_sorted.bam                               ||
||                                                                            ||
||             Output file : counts.txt                                       ||
||                 Summary : counts.txt.summary                               ||
||              Paired-end : yes                                              ||
||        Count read pairs : no                                               ||
||              Annotation : Homo_sapiens.GRCh38.110.gtf (GTF)                ||
||      Dir for temp files : ./                                               ||
||                                                                            ||
||                 Threads : 2                                                ||
||                   Level : meta-feature level                               ||
||      Multimapping reads : not counted                                      ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\============================================================================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file Homo_sapiens.GRCh38.110.gtf ...                       ||
||    Features : 1649677                                                      ||
||    Meta-features : 62754                                                   ||
||    Chromosomes/contigs : 47                                                ||
||                                                                            ||
|| Process BAM file aligned_sorted.bam...                                     ||
||    Paired-end reads are included.                                          ||
||    The reads are assigned on the single-end mode.                          ||
||    Total alignments : 47478667                                             ||
||    Successfully assigned alignments : 36826099 (77.6%)                     ||
||    Running time : 1.06 minutes                                             ||
||                                                                            ||
|| Write the final count table.                                               ||
|| Write the read assignment summary.                                         ||
||                                                                            ||
|| Summary of counting results can be found in file "counts.txt.summary"      ||
||                                                                            ||
\\============================================================================//

**View Final Results**

In [14]:
import pandas as pd

df = pd.read_csv("counts.txt", sep="\t", comment="#")
df.head()

,Geneid,Chr,Start,End,Strand,Length,aligned_sorted.bam
0,ENSG00000279928,1;1;1;1;1,182696;183132;183494;183740;183981,182746;183216;183571;183901;184174,+;+;+;+;+,570,1
1,ENSG00000228037,1;1;1,2581560;2583370;2584125,2581650;2583495;2584533,+;+;+,626,2
2,ENSG00000142611,1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;...,3069168;3069183;3069197;3069203;3069211;318612...,3069296;3069296;3069296;3069296;3069296;318647...,+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;+;...,9767,155
3,ENSG00000284616,1;1;1;1,5301928;5303328;5304401;5306942,5302004;5303393;5305029;5307394,-;-;-;-,1225,0
4,ENSG00000157911,1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;...,2403964;2403974;2404061;2404613;2404838;240503...,2405834;2405834;2404371;2404891;2405828;240583...,-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;-;...,3782,400

In [15]:
# Example: adjust column names based on your file
counts = df.iloc[:, -1:]   # last column = aligned_sorted.bam

# Add gene IDs
counts.index = df.iloc[:, 0]

counts.head()

                 aligned_sorted.bam
Geneid
ENSG00000279928                   1
ENSG00000228037                   2
ENSG00000142611                 155
ENSG00000284616                   0
ENSG00000157911                 400